# Generated by Django 4.1.1 on 2022-10-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("decs", models.TextField()),
                ("batch_number", models.IntegerField()),
                ("in_stock", models.BooleanField()),
            ],
        ),
    ]
